users:
  admin:
    privileged:
      tools:
        kernel/sysctl:
          allowed: true
  unpriviliged:
    privileged:
      tools: {}
      resources: {}
  testuser:
    privileged:
      tools:
        files/list:
          allowed: true
          paths:
            - /
        disks/free:
          allowed: true
        disks/usage:
          allowed: true
        processes/delete:
          allowed: true
        network/connections:
          allowed: true
        network/nslookup:
          allowed: true
        network/curl:
          allowed: true
        network/arp:
          allowed: true
        network/ping:
          allowed: true
        memory/usage:
          allowed: true
        cpu/info:
          allowed: true
        cpu/load-average:
          allowed: true
        disks/block-devices:
          allowed: true
        system/os-release:
          allowed: true
      resources:
        devices://usb:
          - "*"
        devices://pci:
          - "*"
        devices://dmi:
          - "*"
        kernel://modules:
          - "*"
        network://routes:
          - "*"
        network://interfaces:
          - "*"