users:
  admin:
    privileged:
      manage_sysctl:
        allowed: true
  testuser:
    privileged:
      list_directory:
        allowed: true
        paths:
          - /var/log
          - /etc
      get_disk_space:
        allowed: true
      get_disk_usage:
        allowed: true